using OpenTK.Graphics.OpenGL4;
using OpenTK.Windowing.Common;
using OpenTK.Windowing.Desktop;

namespace Game1
{

    public class Game : GameWindow
    {
        public const float speed = 2;
        public float WINDOW_WIDTH = 1.6f/0.9f, WINDOW_HEIGHT = 1.0f;

        public Shader levelShader;
        public Texture levelTextureAtlas, hudAtlas, entityAtlas;

        Player player;
        

        private Level levelStore;
        private Level HUD;
        private readonly float[] HUD_Vertices = [
            // health indicator
            -0.875f,-0.875f,0f,0f,0.75f, 1.0f,
            -0.875f,-0.625f,0f,0f,1f, 1.0f,
            -0.625f,-0.625f,0f,0.25f,1f, 1.0f,

            -0.875f,-0.875f,0f,0f,0.75f, 1.0f,
            -0.625f,-0.625f,0f,0.25f,1f, 1.0f,
            -0.625f,-0.875f,0f,0.25f,0.75f, 1.0f,

            // crosshair
            -0.00390625f,-0.03125f,0f,0.25f,0.75f, 1.0f,
            -0.00390625f,0.03125f,0f,0.25f,1f, 1.0f,
            0.00390625f,0.03125f,0f,0.5f,1f, 1.0f,

            -0.00390625f,-0.03125f,0f,0.25f,0.75f, 1.0f,
            0.00390625f,0.03125f,0f,0.5f,1f, 1.0f,
            0.00390625f,-0.03125f,0f,0.5f,0.75f, 1.0f,

            -0.03125f,-0.00390625f,0f,0.25f,0.75f,1.0f,
            -0.03125f,0.00390625f,0f,0.25f,1f,1.0f,
            0.03125f,0.00390625f,0f,0.5f,1f,1.0f,

            -0.03125f,-0.00390625f,0f,0.25f,0.75f,1.0f,
            0.03125f,0.00390625f,0f,0.5f,1f,1.0f,
            0.03125f,-0.00390625f,0f,0.5f,0.75f,1.0f,
        ];
        

        Renderer renderer;
        

// the following line was generated by my IDE to suppress errors. It does not affect the exeecution of the code :
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.

        public Game(int width, int height, string title) : base(GameWindowSettings.Default, new NativeWindowSettings() { ClientSize = (width, height), Title = title })
        {
            // caps framerate to 480 FPS
            UpdateFrequency = 480;

        }

        protected override void OnLoad()
        {
            /// This routine sets up the shaders, textures, level data and buffers for the game

            base.OnLoad();

            renderer = new();
            player = new((0, 0.1f, 0), (0.25f, 0.5f, 0.25f), (0, (float)Math.PI, 0), 100f);


            // --- Level ---
            levelStore = new();
            
            // room 1 decal
            levelStore.levelObjects.Add(new Plane((0.99f, 0, 0), (-1.0f, 0, 0), 0.5f, 0.5f, 4, 0.8f));

            // room 1
            levelStore.levelObjects.Add(new Cube((0, 0, -1.25f), 2.0f, 1.0f, 0.5f, 4));

            levelStore.levelObjects.Add(new Cube((0.625f, 0, 1.25f), 0.75f, 1.0f, 0.5f, 0));
            levelStore.levelObjects.Add(new Cube((-0.625f, 0, 1.25f), 0.75f, 1.0f, 0.5f, 0));

            levelStore.levelObjects.Add(new Cube((-1.25f, 0, 0), 0.5f, 1.0f, 2.0f, 0));
            levelStore.levelObjects.Add(new Cube((1.25f, 0, 0), 0.5f, 1.0f, 2.0f, 0));

            levelStore.levelObjects.Add(new Cube((0, -0.75f, 0), 2.0f, 0.5f, 2.0f, 1));
            levelStore.levelObjects.Add(new Cube((0, 0.75f, 0), 2.0f, 0.5f, 2.0f, 3));

            //corridor
            levelStore.levelObjects.Add(new Cube((0, -0.75f, 1.25f), 0.5f, 0.5f, 0.5f, 2));
            levelStore.levelObjects.Add(new Cube((0, 0.75f, 1.25f), 0.5f, 0.5f, 0.5f, 3));

            // room 2
            levelStore.levelObjects.Add(new Cube((0, -0.75f, 2.5f), 2.0f, 0.5f, 2.0f, 2));
            levelStore.levelObjects.Add(new Cube((0, 0.75f, 2.5f), 2.0f, 0.5f, 2.0f, 3));

            levelStore.levelObjects.Add(new Cube((-1.25f, 0, 2.5f), 0.5f, 1.0f, 2.0f, 0));
            levelStore.levelObjects.Add(new Cube((1.25f, 0, 2.5f), 0.5f, 1.0f, 2.0f, 0));

            levelStore.levelObjects.Add(new Cube((0, 0, 2.5f), 0.25f, 0.25f, 0.25f, 1));

            // white room
            levelStore.levelObjects.Add(new Cube((0, -0.75f, 4.5f), 2.0f, 0.5f, 2.0f, 6));
            levelStore.levelObjects.Add(new Cube((0, 0.75f, 4.5f), 2.0f, 0.5f, 2.0f, 6));

            levelStore.levelObjects.Add(new Cube((-1.25f, 0, 4.5f), 0.5f, 1.0f, 2.0f, 6));
            levelStore.levelObjects.Add(new Cube((1.25f, 0, 4.5f), 0.5f, 1.0f, 2.0f, 6));

            // huge room
            levelStore.levelObjects.Add(new Cube((0, -0.75f, 10.5f), 10.0f, 0.5f, 10.0f, 3));

            // entity test
            levelStore.levelObjects.Add(new Enemy((0, -0.125f, 5.0f), (0.5f, 0.75f), 1, 0, false));
            levelStore.levelObjects.Add(new Enemy((5.0f, -0.125f, 5.0f), (0.5f, 0.75f), 1, 0, false));
            levelStore.levelObjects.Add(new Enemy((-5.0f, -0.125f, 5.0f), (0.5f, 0.75f), 1, 0, false));

            levelStore.levelObjects.Add(new Item((0.0f, -0.25f, 8.0f), (0.5f, 0.5f), 2, +10, false));

            levelStore.Sync_GL_Level();


            // --- HUD ---
            HUD = new();

            // crosshair
            HUD.levelObjects.Add(new Plane((0, 0, 0), (0, 0, 1), 0.0078125f, 0.0625f, 1, 1.0f));
            HUD.levelObjects.Add(new Plane((0, 0, 0), (0, 0, 1), 0.0625f, 0.0078125f, 1, 1.0f));

            // health
            HUD.levelObjects.Add(new Plane((-0.75f, -0.75f, 0), (0, 0, 1), 0.25f, 0.25f, 0, 1.0f));

            GL.BufferData(BufferTarget.ArrayBuffer, levelStore.GL_Level.Length * sizeof(float), levelStore.GL_Level, BufferUsageHint.StreamDraw);
        }

        protected override void OnUpdateFrame(FrameEventArgs e)
        {
            base.OnUpdateFrame(e);
            
            CursorState temp_cstate = CursorState;

            player.Input_Tick(this, KeyboardState, MouseState, ref temp_cstate, levelStore);

            CursorState = temp_cstate;
        }

        protected override void OnRenderFrame(FrameEventArgs args)
        {
            base.OnRenderFrame(args);

            // the code to render the display is very long so I put it in a function inside the renderer class so all the data it uses is also stored in this class
            renderer.RenderFrame(player, levelStore, HUD, WINDOW_WIDTH, WINDOW_HEIGHT);

            SwapBuffers();  // present the final rendered image as the front buffer so we can begin work on the next frame in the back buffer
        }

        protected override void OnUnload()
        {
            // in order to not waste GPU resources, all objects using the GPU must give up their memory.

            GL.BindBuffer(BufferTarget.ArrayBuffer, 0);
            GL.BindVertexArray(0);
            GL.UseProgram(0);

            renderer.Dispose();

            base.OnUnload();
        }
    }
}