using OpenTK.Graphics.OpenGL4;
using OpenTK.Windowing.Common;
using OpenTK.Windowing.Desktop;
using OpenTK.Windowing.GraphicsLibraryFramework;

namespace Game1
{

    public class Game : GameWindow
    {
        public enum GameState
        {
            Menu, Level, Pause, Loading, None
        }

        const bool levelFileLoad = true;

        public const float speed = 2;
        public float WINDOW_WIDTH = 1.6f / 0.9f, WINDOW_HEIGHT = 1.0f;
        bool firstFrame = true;
        public Shader levelShader;
        public Texture levelTextureAtlas, hudAtlas, entityAtlas;

        Player player;

        public GameState gameState = GameState.Menu;

        private Level levelStore;
        private HUD HUD_Object, PauseMenu;

        private Queue<string> LevelNames = [];
        private string[] levelNamesInitial;

        Renderer renderer;


        // the following line was generated by my IDE to suppress errors. It does not affect the exeecution of the code :
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.

        public Game(int width, int height, string title) : base(GameWindowSettings.Default, new NativeWindowSettings() { ClientSize = (width, height), Title = title })
        {
            // caps framerate to 480 FPS unless on macos which is limited to 120
            UpdateFrequency = 480;
            if (OperatingSystem.IsMacOS())
            {
                UpdateFrequency = 120;
            }

        }

        protected override void OnLoad()
        {
            /// This routine sets up the shaders, textures, level data and buffers for the game

            base.OnLoad();

            renderer = new(out bool rendererInitSuccess);
            if (!rendererInitSuccess)
            {
                Console.WriteLine("\nFatal error initialising Renderer");
                Close();
            }
            player = new((0, 0.1f, 0), (0.25f, 0.5f, 0.25f), (0, (float)Math.PI, 0), 100f);

            if (levelFileLoad)
            {
                // load the data to identify level files and their order
#pragma warning disable CS0162 // Unreachable code detected
                try
                {
                    StreamReader levelNames = new(File.Open("Levels/levelNames.txt", FileMode.Open));
                    string? fileHeader = levelNames.ReadLine();
                    if (fileHeader != "ProjectGame 1.0 | Files 2.0")
                    {
                        Console.WriteLine("Level names file is incorrect format");
                        Close();
                    }
                    while (!levelNames.EndOfStream)
                    {
                        string? currentFileName = levelNames.ReadLine();
                        if (currentFileName != null)
                        {
                            LevelNames.Enqueue(currentFileName);
                        }
                    }
                    levelNamesInitial = [.. LevelNames];
                }
                catch (FileNotFoundException)
                {
                    Console.WriteLine("Level names file is missing! Game load cannot continue");
                    Close();
                }
#pragma warning restore CS0162 // Unreachable code detected
            }

            // --- HUD ---
            HUD_Object = new();

            // crosshair
            HUD_Object.AddHUD_Element(new Crosshair());
            HUD_Object.AddHUD_Element(new HealthBar(100f, (-0.7f, -0.8f, 0), 2));
            HUD_Object.AddHUD_Element(new HealthBar(1.0f, (0.7f, -0.8f, 0), 3));

            HUD_Object.AddHUD_Element(new MessageBox((-0.95f, 0.75f), 24f / 720f));

            HUD_Object.AddHUD_Element(new ItemIcon((-0.9f, 0.9f), (0.1f, 0.1f), 4, new HeldItem() { color = HeldItem.Colors.Red, itemType = HeldItem.ItemTypes.Keycard }));
            HUD_Object.AddHUD_Element(new ItemIcon((-0.75f, 0.9f), (0.1f, 0.1f), 5, new HeldItem() { color = HeldItem.Colors.Blue, itemType = HeldItem.ItemTypes.Keycard }));
            HUD_Object.AddHUD_Element(new ItemIcon((-0.6f, 0.9f), (0.1f, 0.1f), 6, new HeldItem() { color = HeldItem.Colors.Green, itemType = HeldItem.ItemTypes.Keycard }));
            HUD_Object.AddHUD_Element(new ItemIcon((-0.45f, 0.9f), (0.1f, 0.1f), 7, new HeldItem() { color = HeldItem.Colors.Yellow, itemType = HeldItem.ItemTypes.Keycard }));
            
            HUD_Object.AddHUD_Element(new WeaponIcon());

            // --- Pause Menu ---
            PauseMenu = new();

            PauseMenu.AddHUD_Element(new Background(0));
            PauseMenu.AddHUD_Element(new TextElement((-0.6f, 0.7f), 32f / 720f, "Pause Menu", true));
            PauseMenu.AddHUD_Element(new TextElement((-0.6f, 0.4f), 32f / 720f, "Press - to quit", true));

            //GL.BufferData(BufferTarget.ArrayBuffer, levelStore.GL_Level.Length * sizeof(float), levelStore.GL_Level, BufferUsageHint.StreamDraw);

        }

        protected override void OnUpdateFrame(FrameEventArgs e)
        {
            base.OnUpdateFrame(e);
            Console.WriteLine(e.Time);

            // fix a specific issue with OpenGL only filling a quarter of the window on MacOS
            if (OperatingSystem.IsMacOS() && firstFrame)
            {
                CenterWindow();
                firstFrame = false;
            }

            switch (gameState)
            {
                case GameState.Menu:
                    if (KeyboardState.IsKeyPressed(Keys.Enter))
                    {
                        gameState = GameState.Loading;
                    }
                    break;
                case GameState.Level:
                    // first check the messagebox to see if the level has been completed
                    if (HUD_Object.HUD_Elements[3].CheckBoolValue())
                    {
                        gameState = GameState.Loading;
                        break;
                    }

                    // handles player input
                    CursorState temp_cstate = CursorState;  // because the CursorState cannot be sent as a ref, the solution is to 
                                                            // create a copy and then reassign the original after modifying the copy

                    for (int i = 0; i < levelStore.levelObjects.Count; i++)
                    {
                        levelStore.levelObjects[i].CheckObjectStateIsCorrect(ref levelStore);
                    }
                    HUD_Object.HUD_Elements[8].UpdateValue(player.weaponIndex);

                    player.Input_Tick(this, KeyboardState, MouseState, ref temp_cstate, ref levelStore, (float)e.Time, ref renderer, ref HUD_Object.HUD_Elements, ref gameState);
                    foreach (Object levelObject in levelStore.levelObjects)
                    {
                        if (levelObject.objectType == Object.ObjectType.Entity)
                        {
                            levelObject.Tick(player.Position, ref player.Health, (float)e.Time, ref levelStore, ref player);
                        }
                    }
                    CursorState = temp_cstate;

                    // manage tinting for flash
                    renderer.TintTick(e.Time);
                    HUD_Object.HUD_Elements[1].UpdateValue(player.Health);
                    HUD_Object.HUD_Elements[2].UpdateValue(player.GetCurrentWeaponMagUsage());
                    HUD_Object.HUD_Elements[3].UpdateValue((float)e.Time);
                    foreach (HUD_Element element in HUD_Object.HUD_Elements)
                    {
                        element.CheckIfEnabled(player.Inventory);
                    }
                    break;
                case GameState.Pause:
                    if (CursorState == CursorState.Grabbed)
                    {
                        CursorState = CursorState.Normal;
                        if (OperatingSystem.IsMacOS())
                        {
                            MousePosition = (Size.X / 2f, Size.Y / 2f);
                        }
                    }
                    
                    if (KeyboardState.IsKeyPressed(Keys.Escape))
                    {
                        gameState = GameState.Level;
                    }
                    else if (KeyboardState.IsKeyPressed(Keys.Minus))
                    {
                        Close();
                    }
                    break;
                case GameState.Loading:
                    if (levelFileLoad)
                    {
#pragma warning disable CS0162 // Unreachable code detected
                        if (LevelNames.Count > 0)
                        {
                            Level.ImportLevelFromFile(LevelNames.Dequeue(), out levelStore);
                            HUD_Object.HUD_Elements[3].UpdateValue(false);
                            player.LevelReset();
                            gameState = GameState.Level;
                        }
                        else
                        {
                            foreach (string levelName in levelNamesInitial)
                            {
                                LevelNames.Enqueue(levelName);
                            }
                            player = new((0, 0.1f, 0), (0.25f, 0.5f, 0.25f), (0, (float)Math.PI, 0), 100f);
                            CursorState = CursorState.Normal;
                            gameState = GameState.Menu;
                        }
#pragma warning restore CS0162 // Unreachable code detected
                    }
                    else
                    {
                        // the following code is used for debugging and creating levels
#pragma warning disable CS0162 // Unreachable code detected
                        levelStore = LevelTemp.level2Return();
#pragma warning restore CS0162 // Unreachable code detected
                        levelStore.ExportToFile("Levels/level2.lvl");
                        Level.ImportLevelFromFile("Levels/level2.lvl", out levelStore);
                        HUD_Object.HUD_Elements[3].UpdateValue(false);
                        player.LevelReset();
                        gameState = GameState.Level;
                        
                    }
                    break;
            }
        }

        protected override void OnRenderFrame(FrameEventArgs args)
        {
            base.OnRenderFrame(args);
            switch (gameState)
            {
                case GameState.Menu:
                    renderer.RenderMainMenu();
                    break;
                case GameState.Level:
                    // the code to render the display is very long so I put it in a function inside the renderer class so all the data it uses is also stored in this class
                    renderer.RenderLevelFrame(player, ref levelStore, HUD_Object, WINDOW_WIDTH, WINDOW_HEIGHT);
                    break;
                case GameState.Loading:
                    // the code to render the display is very long so I put it in a function inside the renderer class so all the data it uses is also stored in this class
                    //renderer.RenderLevelFrame(player, ref levelStore, HUD_Object, WINDOW_WIDTH, WINDOW_HEIGHT);
                    break;
                case GameState.Pause:
                    renderer.RenderLevelFrame(player, ref levelStore, PauseMenu, WINDOW_WIDTH, WINDOW_HEIGHT);
                    break;
            }
            

            SwapBuffers();  // present the final rendered image as the front buffer so we can begin work on the next frame in the back buffer
        }

        protected override void OnUnload()
        {
            // in order to not waste GPU resources, all objects using the GPU must give up their memory.

            GL.BindBuffer(BufferTarget.ArrayBuffer, 0);
            GL.BindVertexArray(0);
            GL.UseProgram(0);

            renderer.Dispose();

            base.OnUnload();
        }

        protected override void OnResize(ResizeEventArgs e)
        {
            // when moving or resizing the window, this code changes the size of the OpenGL viewport to fill the window

            base.OnResize(e);

            GL.Viewport(0, 0, e.Width, e.Height);
        }
    }
}