using OpenTK.Graphics.OpenGL4;
using OpenTK.Windowing.Common;
using OpenTK.Windowing.Desktop;
using OpenTK.Windowing.GraphicsLibraryFramework;
using OpenTK.Mathematics;
using OpenTK.Audio.OpenAL;
using System.ComponentModel.DataAnnotations.Schema;

namespace Game1
{

    public class Game : GameWindow
    {
        public const float speed = 1/ 240f;
        public float WINDOW_WIDTH = 1.6f/0.9f, WINDOW_HEIGHT = 1.0f;

        public Shader levelShader;
        public Texture levelTextureAtlas, hudAtlas, entityAtlas;

        private int VertexBufferObject;
        private int VertexArrayObject;

        private Vector3 Position;
        private Vector3 playerScale = (0.25f, 0.5f, 0.25f);
        private Vector3 moveRotation;
        private Vector3 upRotation;
        private Vector3 front;
        private float health = 100;

        private Level levelStore;

        private float[] GL_Level = [];
        private readonly float[] HUD_Vertices = [
            // health indicator
            -0.875f,-0.875f,0f,0f,0.75f, 1.0f,
            -0.875f,-0.625f,0f,0f,1f, 1.0f,
            -0.625f,-0.625f,0f,0.25f,1f, 1.0f,

            -0.875f,-0.875f,0f,0f,0.75f, 1.0f,
            -0.625f,-0.625f,0f,0.25f,1f, 1.0f,
            -0.625f,-0.875f,0f,0.25f,0.75f, 1.0f,

            // crosshair
            -0.00390625f,-0.03125f,0f,0.25f,0.75f, 1.0f,
            -0.00390625f,0.03125f,0f,0.25f,1f, 1.0f,
            0.00390625f,0.03125f,0f,0.5f,1f, 1.0f,

            -0.00390625f,-0.03125f,0f,0.25f,0.75f, 1.0f,
            0.00390625f,0.03125f,0f,0.5f,1f, 1.0f,
            0.00390625f,-0.03125f,0f,0.5f,0.75f, 1.0f,

            -0.03125f,-0.00390625f,0f,0.25f,0.75f,1.0f,
            -0.03125f,0.00390625f,0f,0.25f,1f,1.0f,
            0.03125f,0.00390625f,0f,0.5f,1f,1.0f,

            -0.03125f,-0.00390625f,0f,0.25f,0.75f,1.0f,
            0.03125f,0.00390625f,0f,0.5f,1f,1.0f,
            0.03125f,-0.00390625f,0f,0.5f,0.75f,1.0f,
        ];
        List<float> GL_Entity = [];
        

// the following line was generated by my IDE to suppress errors. It does not affect the exeecution of the code :
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.

        public Game(int width, int height, string title) : base(GameWindowSettings.Default, new NativeWindowSettings() { ClientSize = (width, height), Title = title })
        {
            UpdateFrequency = 480;

        }

        protected override void OnLoad()
        {
            /// This routine sets up the shaders, textures and buffers for the game
            /// 

            base.OnLoad();

            GL.ClearColor(0.2f, 0.2f, 0.5f, 1.0f);

            VertexArrayObject = GL.GenVertexArray();
            GL.BindVertexArray(VertexArrayObject);

            VertexBufferObject = GL.GenBuffer();
            GL.BindBuffer(BufferTarget.ArrayBuffer, VertexBufferObject);

            levelTextureAtlas = new("Textures/atlas.png", TextureUnit.Texture0);
            hudAtlas = new("Textures/hudatlas.png", TextureUnit.Texture1);
            entityAtlas = new("Textures/entityatlas.png", TextureUnit.Texture2);

            levelShader = new("Shaders/level.vert", "Shaders/level.frag");
            levelShader.Use(Matrix4.Identity, Matrix4.Identity, Matrix4.Identity);

            int vertexLocation = GL.GetAttribLocation(levelShader.Handle, "aPosition");
            GL.EnableVertexAttribArray(vertexLocation);
            GL.VertexAttribPointer(vertexLocation, 3, VertexAttribPointerType.Float, false, 6 * sizeof(float), 0);

            int textureLocation = GL.GetAttribLocation(levelShader.Handle, "aTexCoord");
            GL.EnableVertexAttribArray(textureLocation);
            GL.VertexAttribPointer(textureLocation, 2, VertexAttribPointerType.Float, false, 6 * sizeof(float), 3 * sizeof(float));

            int shaderDirection = GL.GetAttribLocation(levelShader.Handle, "aShaderDir");
            GL.EnableVertexAttribArray(shaderDirection);
            GL.VertexAttribPointer(shaderDirection, 1, VertexAttribPointerType.Float, false, 6 * sizeof(float), 5 * sizeof(float));

            levelShader.SetInt("texture1", 0);
            levelShader.SetInt("texture2", 1);
            levelShader.SetInt("texture3", 2);

            GL.Enable(EnableCap.DepthTest);
            front = (0.0f, 0.0f, -1.0f);
            Position = new(0, 0.1f, 0);
            moveRotation = new(0, (float)Math.PI, 0);

            levelStore = new();
            
            // room 1 decal
            levelStore.levelObjects.Add(new Plane((0.99f, 0, 0), (-1.0f, 0, 0), 0.5f, 0.5f, 4, 0.8f));

            // room 1
            levelStore.levelObjects.Add(new Cube((0, 0, -1.25f), 2.0f, 1.0f, 0.5f, 4));

            levelStore.levelObjects.Add(new Cube((0.625f, 0, 1.25f), 0.75f, 1.0f, 0.5f, 0));
            levelStore.levelObjects.Add(new Cube((-0.625f, 0, 1.25f), 0.75f, 1.0f, 0.5f, 0));

            levelStore.levelObjects.Add(new Cube((-1.25f, 0, 0), 0.5f, 1.0f, 2.0f, 0));
            levelStore.levelObjects.Add(new Cube((1.25f, 0, 0), 0.5f, 1.0f, 2.0f, 0));

            levelStore.levelObjects.Add(new Cube((0, -0.75f, 0), 2.0f, 0.5f, 2.0f, 1));
            levelStore.levelObjects.Add(new Cube((0, 0.75f, 0), 2.0f, 0.5f, 2.0f, 3));

            //corridor
            levelStore.levelObjects.Add(new Cube((0, -0.75f, 1.25f), 0.5f, 0.5f, 0.5f, 2));
            levelStore.levelObjects.Add(new Cube((0, 0.75f, 1.25f), 0.5f, 0.5f, 0.5f, 3));

            // room 2
            levelStore.levelObjects.Add(new Cube((0, -0.75f, 2.5f), 2.0f, 0.5f, 2.0f, 2));
            levelStore.levelObjects.Add(new Cube((0, 0.75f, 2.5f), 2.0f, 0.5f, 2.0f, 3));

            levelStore.levelObjects.Add(new Cube((-1.25f, 0, 2.5f), 0.5f, 1.0f, 2.0f, 0));
            levelStore.levelObjects.Add(new Cube((1.25f, 0, 2.5f), 0.5f, 1.0f, 2.0f, 0));

            levelStore.levelObjects.Add(new Cube((0, 0, 2.5f), 0.25f, 0.25f, 0.25f, 1));

            // white room
            levelStore.levelObjects.Add(new Cube((0, -0.75f, 4.5f), 2.0f, 0.5f, 2.0f, 6));
            levelStore.levelObjects.Add(new Cube((0, 0.75f, 4.5f), 2.0f, 0.5f, 2.0f, 6));

            levelStore.levelObjects.Add(new Cube((-1.25f, 0, 4.5f), 0.5f, 1.0f, 2.0f, 6));
            levelStore.levelObjects.Add(new Cube((1.25f, 0, 4.5f), 0.5f, 1.0f, 2.0f, 6));

            //levelStore.levelObjects.Add(new Cube((0, 0, 5.75f), 2.0f, 1.0f, 0.5f, 4));

            // huge room
            levelStore.levelObjects.Add(new Cube((0, -0.75f, 10.5f), 10.0f, 0.5f, 10.0f, 3));

            // entity test
            levelStore.levelObjects.Add(new Enemy((0, -0.125f, 5.0f), (0.5f, 0.75f), 1, 0, false));
            levelStore.levelObjects.Add(new Enemy((5.0f, -0.125f, 5.0f), (0.5f, 0.75f), 1, 0, false));
            levelStore.levelObjects.Add(new Enemy((-5.0f, -0.125f, 5.0f), (0.5f, 0.75f), 1, 0, false));

            levelStore.levelObjects.Add(new Item((0.0f, -0.25f, 8.0f), (0.5f, 0.5f), 2, +10, false));

            LoadLevelGL();

            GL.BufferData(BufferTarget.ArrayBuffer, GL_Level.Length * sizeof(float), GL_Level, BufferUsageHint.StreamDraw);
        }

        protected override void OnUpdateFrame(FrameEventArgs e)
        {
            base.OnUpdateFrame(e);

            Vector3 tempZ = new(0), tempX = new(0), tempY = new(0);

            if (KeyboardState.IsKeyDown(Keys.Escape))
            {
                Close();
            }

            // input handler (rotation using euler angles)
            if (KeyboardState.IsKeyDown(Keys.Right))
            {
                moveRotation.Y += (float)(Math.PI / 600.0);
            }
            if (KeyboardState.IsKeyDown(Keys.Left))
            {
                moveRotation.Y -= (float)(Math.PI / 600.0);
            }

            if (KeyboardState.IsKeyDown(Keys.Down))
            {
                upRotation.X += (float)(Math.PI / 600.0);
                if (upRotation.X > Math.PI * 0.45f)
                {
                    upRotation.X = (float)(Math.PI * 0.45f);
                }
            }
            if (KeyboardState.IsKeyDown(Keys.Up))
            {
                upRotation.X -= (float)(Math.PI / 600.0);
                if (upRotation.X < -Math.PI * 0.45f)
                {
                    upRotation.X = -(float)(Math.PI * 0.45f);
                }
            }

            Vector3 front3 = Matrix3.CreateRotationY(moveRotation.Y) * new Vector3(0f, 0f, -1f);

            // player input handler (movement)

            if (KeyboardState.IsKeyDown(Keys.W))
            {
                tempZ += front3 * speed;
            }
            if (KeyboardState.IsKeyDown(Keys.S))
            {
                tempZ -= front3 * speed;
            }

            if (KeyboardState.IsKeyDown(Keys.D))
            {
                tempX += Vector3.Normalize(Vector3.Cross(front3, (0, 1, 0))) * speed;
            }
            if (KeyboardState.IsKeyDown(Keys.A))
            {
                tempX -= Vector3.Normalize(Vector3.Cross(front3, (0, 1, 0))) * speed;
            }

            if (KeyboardState.IsKeyDown(Keys.E))
            {
                tempY.Y += speed;
            }
            if (KeyboardState.IsKeyDown(Keys.Q))
            {
                tempY.Y -= speed;
            }

            /*if (KeyboardState.IsKeyDown(Keys.Space))
            {
                tempY.Y += 15 * speed;
            }*/


            // collision detection
            bool collidedZ = false;
            bool collidedX = false;
            bool collidedXZ = false;
            bool collidedY = false;
            bool grounded = false;

            foreach (Object levelObject in levelStore.levelObjects)
            {
                if (levelObject.objectType != Object.ObjectType.Entity)
                {
                    // to simplify this part of the code, CheckCollision is a virtual function of Object and is overridden in inheriting classes
                    collidedZ |= levelObject.CheckCollision(Position + tempZ + (new Vector3(0, 1, 0) * speed), playerScale);
                    collidedX |= levelObject.CheckCollision(Position + tempX + (new Vector3(0, 1, 0) * speed), playerScale);
                    collidedXZ |= levelObject.CheckCollision(Position + (tempX + tempZ) + tempY, playerScale);
                    collidedY |= levelObject.CheckCollision(Position + (tempY), playerScale);
                    if (levelObject.objectType == Object.ObjectType.Cube)
                    {
                        Cube C = (Cube)levelObject;
                        if (C.centre.Y < Position.Y && collidedY)
                        {
                            grounded = true;
                            Position.Y = C.centre.Y + (playerScale.Y / 2) + (C.scaleY / 2) + (speed / 2);
                        }
                    }
                }
                else
                {
                    levelObject.Tick(Position, ref health);
                }


            }
            if (grounded)
            {
            }
            else
            {
                Position.Y -= speed / 5;
            }

            if (!collidedXZ)
            {
                Position += tempZ + tempX;
            }
            else if (!collidedZ)
            {
                Position += tempZ;
                if (collidedX)
                {
                    Position -= Vector3.Normalize(Vector3.Cross(front3, (0, 1, 0))) * speed;
                }
            }
            else if (!collidedX)
            {
                Position += tempX;
            }


        }

        public void LoadLevelGL()
        {
            GL_Level = levelStore.ExportToOpenGLFormat();
        }

        protected override void OnRenderFrame(FrameEventArgs args)
        {
            base.OnRenderFrame(args);

            GL.Enable(EnableCap.DepthTest);     // when drawing level geometry, we need the depth buffer enabled so that the triangles are drawn in the correct order 

            GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);

            /// Draw the Level Geometry

            GL.BufferData(BufferTarget.ArrayBuffer, GL_Level.Length * sizeof(float), GL_Level, BufferUsageHint.StreamDraw);

            GL.BindVertexArray(VertexArrayObject);

            // generate the correct transformation matrices
            Matrix4 model = Matrix4.CreateRotationX(moveRotation.X);

            front = Matrix3.CreateFromQuaternion(Quaternion.FromEulerAngles(upRotation + moveRotation))  * new Vector3(0.0f, 0.0f, -1.0f); // by treating the rotations as euler angles and keeping them separate in the code, I can move the player by rotating only around the Y axis, while being able to look up and down as well as around the Y axis. Treating them as euler angles also means I can look around the 'pitch' axis without having to calculate this in the player movement code

            Matrix4 view = Matrix4.LookAt(Position + (Vector3.UnitY * playerScale.Y / 2) , Position+ (Vector3.UnitY * playerScale.Y / 2) + (front.X, front.Y, front.Z), (0, 1, 0));

            Matrix4 projection = Matrix4.CreatePerspectiveFieldOfView((float)(Math.PI / 3), WINDOW_WIDTH / WINDOW_HEIGHT, 0.1f, 100.0f);

            // enable the correct texture atlas for the level
            levelTextureAtlas.Use(TextureUnit.Texture0);
            levelShader.SetInt("textureAtlas", 0);
            levelShader.Use(model, view, projection);

            GL.DrawArrays(PrimitiveType.Triangles, 0, GL_Level.Length / 6);

            /// Begin drawing entities
            Entity entityTemp;
            GL_Entity = [];
            foreach (Object objEntity in levelStore.levelObjects)
            {
                if (objEntity.objectType == Object.ObjectType.Entity)
                {
                    entityTemp = (Entity)objEntity;
                    GL_Entity.AddRange(entityTemp.GenerateOpenGLData(upRotation + moveRotation));
                }
            }
            float[] GL_EntityArray = [.. GL_Entity];

            levelShader.SetInt("textureAtlas", 2);

            GL.BufferData(BufferTarget.ArrayBuffer, GL_EntityArray.Length * sizeof(float), GL_EntityArray, BufferUsageHint.StreamDraw); // buffer the Entity vertex data to the GPU. Entities are drawn like 2D sprites so their vertex data needs to be updated every frame
            levelShader.Use(model, view, projection);
            GL.DrawArrays(PrimitiveType.Triangles, 0, GL_EntityArray.Length / 6);

            // skybox
            Triangle[] skybox_triangles = new Cube(Position, 50, 50, 50, 15).ConvertToTriangles();

            List<float> skybox = [];

            foreach (Triangle tempTriangle in skybox_triangles)
            {
                for (int i = 0; i < 3; i++)
                {
                    skybox.AddRange(tempTriangle.coordinates[i].X, tempTriangle.coordinates[i].Y, tempTriangle.coordinates[i].Z, tempTriangle.textureCoordinates[i].X, tempTriangle.textureCoordinates[i].Y, tempTriangle.directionIndex);
                }
            }

            levelTextureAtlas.Use(TextureUnit.Texture0);
            levelShader.SetInt("textureAtlas", 0);

            GL.BufferData(BufferTarget.ArrayBuffer, skybox.Count * sizeof(float), skybox.ToArray(), BufferUsageHint.StreamDraw); // buffer the Entity 
            levelShader.Use(model, view, projection);
            GL.DrawArrays(PrimitiveType.Triangles, 0, skybox.Count / 6);

            /// Begin Drawing the UI

            GL.Disable(EnableCap.DepthTest);    // disable the depth test to prevent the level geometry from obscuring the HUD

            GL.BufferData(BufferTarget.ArrayBuffer, HUD_Vertices.Length * sizeof(float), HUD_Vertices, BufferUsageHint.StreamDraw); // buffer the HUD vertex data to the GPU

            // Change texture atlas to the correct atlas for the HUD
            hudAtlas.Use(TextureUnit.Texture1);
            levelShader.SetInt("textureAtlas", 1);

            levelShader.Use(Matrix4.Identity, Matrix4.Identity, Matrix4.Identity);  // we can reuse the level shader by adding all relevant parameters in such as way that the vertex shader applies no transformations and the fragment shader applies no shading (shaded dir = 1.0f)

            GL.DrawArrays(PrimitiveType.Triangles, 0, HUD_Vertices.Length / 6); // finally, we can tell the GPU to draw the HUD

            SwapBuffers();  // present the final rendered image as the front buffer so we can begin work on the next frame in the back buffer
        }

        protected override void OnUnload()
        {
            GL.BindBuffer(BufferTarget.ArrayBuffer, 0);
            GL.BindVertexArray(0);
            GL.UseProgram(0);

            GL.DeleteBuffer(VertexBufferObject);
            GL.DeleteBuffer(VertexArrayObject);

            levelShader.Dispose();

            base.OnUnload();
        }
    }

}