using OpenTK.Mathematics;
using OpenTK.Graphics.OpenGL;

namespace Game1 {
    public class Object
    {
        public enum ObjectType
        {
            None = 0, Triangle= 1, Plane = 2, Entity = 3, Cube = 4
        }
        public ObjectType objectType;

        public virtual Triangle[] ConvertToTriangles()
        {
            return [];
        }

        public virtual bool CheckCollision(Vector3 input, Vector3 playerScale)
        {
            return false;
        }

        public virtual void Tick(Vector3 playerPosition, ref float health)
        {
            
        }

    }
    public class Triangle : Object
    {
        public Vector3[] coordinates;
        public Vector2[] textureCoordinates;
        public float directionIndex;

        public Triangle(Vector3 v1, Vector3 v2, Vector3 v3, Vector2[] textureCoordinatesIn, int textureIndex, float directionshade)
        {
            objectType = ObjectType.Triangle;
            coordinates = [v1, v2, v3];

            textureCoordinates = new Vector2[3];
            directionIndex = directionshade;
            for (int i = 0; i < textureCoordinatesIn.Length; i++)
            {
                textureCoordinates[i] = textureCoordinatesIn[i];
            }
        }

        public static void LoadTriangleFromFile(out Triangle triangleOutput, ref BinaryReader levelReader)
        {
            Vector3 v1, v2, v3;
            Vector2 tc1, tc2, tc3;
            byte textureIndex;
            float directionIndex;
            v1 = new(levelReader.ReadSingle(), levelReader.ReadSingle(), levelReader.ReadSingle());
            v2 = new(levelReader.ReadSingle(), levelReader.ReadSingle(), levelReader.ReadSingle());
            v3 = new(levelReader.ReadSingle(), levelReader.ReadSingle(), levelReader.ReadSingle());

            tc1 = new(levelReader.ReadSingle(), levelReader.ReadSingle());
            tc2 = new(levelReader.ReadSingle(), levelReader.ReadSingle());
            tc3 = new(levelReader.ReadSingle(), levelReader.ReadSingle());

            textureIndex = levelReader.ReadByte();
            directionIndex = levelReader.ReadSingle();

            triangleOutput = new(v1, v2, v3, [tc1, tc2, tc3], textureIndex, directionIndex);
        }
    }

    public class Cube : Object
    {
        public float scaleX, scaleY, scaleZ;
        public Vector3 centre;
        readonly Vector3[] vertexCoordinates;
        readonly int textureIndex;
        // vertex indices references the cube coordinates that are generated in the initialiser
        readonly int[] vertexindices = [
            0, 1, 2, 1, 2, 3,       // negative x face
            4, 5, 6, 5, 6, 7,       // positive x face
            0, 1, 4, 1, 4, 5,       // positive y face
            2, 3, 6, 3, 6, 7,       // negative y face
            1, 3, 5, 3, 5, 7,       // positive z face
            0, 2, 4, 2, 4, 6        // negative z face
        ];
        readonly float[] directions = [0.7f, 0.9f, 1.0f, 0.6f, 0.8f, 0.8f];
        readonly int[] textureCoordIndices = [      // used to reference the correct texute coordinates when a cube is generated by the program

            2, 0, 3, 0, 3, 1,       // negative x face
            0, 2, 1, 2, 1, 3,       // positive x face
            1, 0, 3, 0, 3, 2,       // positive y face
            0, 1, 2, 1, 2, 3,       // negative y face
            2, 3, 0, 3, 0, 1,       // positive z face
            0, 1, 2, 1, 2, 3,       // negative z face

        ];
        Vector2[] textureCoordinates;
            
        // this initializer assigns and calculates all the properties of the cube type based on the parameters provided
        public Cube(Vector3 centrein, float scaleXin, float scaleYin, float scaleZin, int TextureIndexIn)
        {
            objectType = ObjectType.Cube;
            scaleX = scaleXin;
            scaleY = scaleYin;
            scaleZ = scaleZin;
            centre = centrein;

            textureIndex = TextureIndexIn;

            /// textures in OpenGL are stored as an image and addressed by a (0,0) to (1,1) UV space.
            /// this project uses a texture atlas to store all the textures used so a texture index in the atlas 
            /// must be converted to UV space before OpenGL can process it
            textureCoordinates = [
                new(textureIndex % 4 * 0.25f, (4 - (textureIndex >> 2)) * 0.25f),
                new(textureIndex % 4 * 0.25f, (3 - (textureIndex >> 2)) * 0.25f),
                new((1 + (textureIndex % 4)) * 0.25f, (4 - (textureIndex >> 2)) * 0.25f),
                new((1 + (textureIndex % 4)) * 0.25f, (3 - (textureIndex >> 2)) * 0.25f),
            ];

            // vertex coordinates are used when converting this object to the format used by OpenGL and the shaders
            vertexCoordinates = [
                centre + (Vector3.UnitX * scaleX / 2) + (Vector3.UnitY * scaleY / 2) - (Vector3.UnitZ * scaleZ / 2),
                centre + (Vector3.UnitX * scaleX / 2) + (Vector3.UnitY * scaleY / 2) + (Vector3.UnitZ * scaleZ / 2),
                centre + (Vector3.UnitX * scaleX / 2) - (Vector3.UnitY * scaleY / 2) - (Vector3.UnitZ * scaleZ / 2),
                centre + (Vector3.UnitX * scaleX / 2) - (Vector3.UnitY * scaleY / 2) + (Vector3.UnitZ * scaleZ / 2),
                centre - (Vector3.UnitX * scaleX / 2) + (Vector3.UnitY * scaleY / 2) - (Vector3.UnitZ * scaleZ / 2),
                centre - (Vector3.UnitX * scaleX / 2) + (Vector3.UnitY * scaleY / 2) + (Vector3.UnitZ * scaleZ / 2),
                centre - (Vector3.UnitX * scaleX / 2) - (Vector3.UnitY * scaleY / 2) - (Vector3.UnitZ * scaleZ / 2),
                centre - (Vector3.UnitX * scaleX / 2) - (Vector3.UnitY * scaleY / 2) + (Vector3.UnitZ * scaleZ / 2)
            ];
        }

        public override bool CheckCollision(Vector3 input, Vector3 playerScale)
        {
            // this checks if any vertex of the player's hitbox (an AABB defined by input and player scale) lies within the bounds of the AABB of the cube
            if (centre.X + scaleX / 2 > input.X - (playerScale.X / 2) && centre.X - scaleX / 2 < input.X + (playerScale.X / 2))
            {
                if (centre. Y + scaleY / 2 > input.Y - (playerScale.Y / 2) && centre.Y - scaleY / 2 < input.Y + (playerScale.Y / 2))
                {
                    if (centre.Z + scaleZ / 2 > input.Z - (playerScale.Z / 2) && centre.Z - scaleZ / 2 < input.Z + (playerScale.Z / 2))
                    {
                        return true;
                    }
                }
            }

            return false;
        }

        public override Triangle[] ConvertToTriangles()
        {
            // OpenGL only has full support for processing triangles so any more complex shapes need to be converted down to triangles

            List<Triangle> TriangleList = [];

            for (int i = 0; i < vertexindices.Length / 3; i++)
            {
                Triangle triTemp = new(vertexCoordinates[vertexindices[i * 3]], vertexCoordinates[vertexindices[(i * 3) + 1]], vertexCoordinates[vertexindices[(i * 3) + 2]], [textureCoordinates[textureCoordIndices[(i * 3) + 0]], textureCoordinates[textureCoordIndices[(i * 3) + 1]], textureCoordinates[textureCoordIndices[(i * 3) + 2]]], 0, directions[i / 2]);
                TriangleList.Add(triTemp);
            }

            return [.. TriangleList];
        }
    }

    public class Plane : Object
    {
        private Vector3 centre, normal;
        private readonly float width, height;
        private readonly int textureIndex;
        public readonly float directionIndex;

        Vector3 UnitRight, UnitUp;

        public Vector3[] RectangleCoordinates = new Vector3[4];

        public Plane(Vector3 centreIn, Vector3 normalIn, float widthIn, float heightIn, int textureIndexIn, float directionIndexIn)
        {
            if (normal != Vector3.UnitY && normal != -Vector3.UnitY)
            {
                UnitRight = Vector3.Normalize(Vector3.Cross(normal, -Vector3.UnitY));
            }
            else
            {
                UnitRight = Vector3.Normalize(Vector3.Cross(normal, -Vector3.UnitZ));
            }
            UnitUp = Vector3.Normalize(Vector3.Cross(-UnitRight, normal));


            objectType = ObjectType.Plane;

            centre = centreIn;
            normal = normalIn;
            width = widthIn;
            height = heightIn;
            textureIndex = textureIndexIn;
            directionIndex = directionIndexIn;

            RectangleCoordinates[0] = centre - (UnitUp * 0.5f * height) - (UnitRight * 0.5f * width);
            RectangleCoordinates[1] = centre + (UnitUp * 0.5f * height) - (UnitRight * 0.5f * width);
            RectangleCoordinates[2] = centre + (UnitUp * 0.5f * height) + (UnitRight * 0.5f * width);
            RectangleCoordinates[3] = centre - (UnitUp * 0.5f * height) + (UnitRight * 0.5f * width);
        }

        public override Triangle[] ConvertToTriangles()
        {
            // OpenGL only has full support for processing triangles so any more complex shapes need to be converted down to triangles

            Triangle[] returnTriangles = new Triangle[2];

            if (normal != Vector3.UnitY && normal != -Vector3.UnitY)
            {
                UnitRight = Vector3.Normalize(Vector3.Cross(normal, -Vector3.UnitY));
            }
            else
            {
                UnitRight = Vector3.Normalize(Vector3.Cross(normal, -Vector3.UnitZ));
            }
            UnitUp = Vector3.Normalize(Vector3.Cross(-UnitRight, normal));

            RectangleCoordinates[0] = centre - (UnitUp * 0.5f * height) - (UnitRight * 0.5f * width);
            RectangleCoordinates[1] = centre + (UnitUp * 0.5f * height) - (UnitRight * 0.5f * width);
            RectangleCoordinates[2] = centre + (UnitUp * 0.5f * height) + (UnitRight * 0.5f * width);
            RectangleCoordinates[3] = centre - (UnitUp * 0.5f * height) + (UnitRight * 0.5f * width);

            Vector2[] TextureCoordinates =
            [
                new(textureIndex % 4 * 0.25f, (3 - (textureIndex >> 2)) * 0.25f),
                new(textureIndex % 4 * 0.25f, (4 - (textureIndex >> 2)) * 0.25f),
                new((1 + (textureIndex % 4)) * 0.25f, (4 - (textureIndex >> 2)) * 0.25f),
                new((1 + (textureIndex % 4)) * 0.25f, (3 - (textureIndex >> 2)) * 0.25f),
            ];

            returnTriangles[0] = new(RectangleCoordinates[0], RectangleCoordinates[1], RectangleCoordinates[2], TextureCoordinates[0..3], textureIndex, directionIndex);
            returnTriangles[1] = new(RectangleCoordinates[0], RectangleCoordinates[2], RectangleCoordinates[3], [TextureCoordinates[0], TextureCoordinates[2], TextureCoordinates[3]], textureIndex, directionIndex);

            return returnTriangles;
        }

        public static void LoadPlaneFromFile(out Plane plane, ref BinaryReader levelReader)
        {
            Vector3 centreTemp, normalTemp;
            float widthTemp, heightTemp;
            int textureIndexTemp;

            float directionIndexIn;

            centreTemp = new(levelReader.ReadSingle(), levelReader.ReadSingle(), levelReader.ReadSingle());
            normalTemp = new(levelReader.ReadSingle(), levelReader.ReadSingle(), levelReader.ReadSingle());
            widthTemp = levelReader.ReadSingle();
            heightTemp = levelReader.ReadSingle();
            textureIndexTemp = levelReader.ReadInt32();
            directionIndexIn = levelReader.ReadByte();

            plane = new(centreTemp, normalTemp, widthTemp, heightTemp, textureIndexTemp, directionIndexIn);
        }

        public override bool CheckCollision(Vector3 coordinate, Vector3 playerScale)
        {
            float distanceToPlane, distanceToCentre;
            float d = Vector3.Dot(normal, centre);
            if (normal.Length > 0)
            {
                distanceToPlane = Math.Abs((normal.X * coordinate.X) + (normal.Y * coordinate.Y) + (normal.Z * coordinate.Z) - d) / normal.Length;
            }
            else
            {
                return false;
            }

            if (distanceToPlane < Game.speed * 60)
            {
                Vector3 PointOnPlane;
                if (Math.Sign(Vector4.Dot(new Vector4(normal, d), new Vector4(centre, 1.0f))) == Math.Sign(Vector4.Dot(new Vector4(normal, d), new Vector4(coordinate, 1.0f))))
                {
                    PointOnPlane = coordinate - (Vector3.Normalize(normal) * distanceToPlane);
                }
                else
                {
                    PointOnPlane = coordinate + (Vector3.Normalize(normal) * distanceToPlane);
                }

                Vector3 vectorToCentre = PointOnPlane - coordinate;
                distanceToCentre = vectorToCentre.Length;

                if (distanceToCentre < ((width / 2 * UnitRight) + (height / 2 * UnitUp)).Length)
                {
                    float areaSum = 0;
                    float totalArea = width * height;

                    areaSum += CustomVector3Extension.CalculateArea(RectangleCoordinates[0], PointOnPlane, RectangleCoordinates[3]);
                    areaSum += CustomVector3Extension.CalculateArea(RectangleCoordinates[3], PointOnPlane, RectangleCoordinates[2]);
                    areaSum += CustomVector3Extension.CalculateArea(RectangleCoordinates[2], PointOnPlane, RectangleCoordinates[1]);
                    areaSum += CustomVector3Extension.CalculateArea(PointOnPlane, RectangleCoordinates[1], RectangleCoordinates[0]);

                    if (areaSum < 1.05 * totalArea)
                    {
                        return true;
                    }
                    else
                    {
                        return false;
                    }
                }
                else
                {
                    return false;
                }
            }
            else
            {
                return false;
            }
        }
    }

    

    public class CustomVector3Extension {

        public static float CalculateArea(Vector3 p1, Vector3 p2, Vector3 p3)
        {
            float length1, length2;
            double angle;

            length1 = (p1 - p2).Length;
            length2 = (p1 - p3).Length;

            angle = Math.Acos(Vector3.Dot(p1 - p2, p1 - p3) / (length1 * length2));

            return (float)(0.5 * Math.Sin(angle) * length1 * length2);

        } 

    }

    public class Level
    {

        public List<Object> levelObjects;

        public Level()
        {
            levelObjects = [];
        }

        public float[] ExportToOpenGLFormat()
        {
            List<float> levelOpenGL = [];

            int[] indices = [0, 1, 2, 0, 2, 3];

            // All object types in the level must be converted to OpenGL triangle data before they can be processed by the GPU during rendering

            foreach (Object levelObject in levelObjects)
            {
                if (levelObject.objectType == Object.ObjectType.Triangle)
                {
                    Triangle tempTriangle = (Triangle)levelObject;
                    for (int i = 0; i < 3; i++)
                    {
                        levelOpenGL.AddRange(tempTriangle.coordinates[i].X, tempTriangle.coordinates[i].Y, tempTriangle.coordinates[i].Z, tempTriangle.textureCoordinates[i].X, tempTriangle.textureCoordinates[i].Y, tempTriangle.directionIndex);
                    }
                }
                else if (levelObject.objectType == Object.ObjectType.Plane)
                {
                    foreach (Triangle triangle in levelObject.ConvertToTriangles())
                    {
                        for (int i = 0; i < 3; i++)
                        {
                            levelOpenGL.AddRange(triangle.coordinates[i].X, triangle.coordinates[i].Y, triangle.coordinates[i].Z, triangle.textureCoordinates[i].X, triangle.textureCoordinates[i].Y, triangle.directionIndex);
                        }
                    }
                }
                else if (levelObject.objectType == Object.ObjectType.Cube)
                {
                    Cube cubeTemp = (Cube)levelObject;
                    foreach (Triangle triangle in cubeTemp.ConvertToTriangles())
                    {
                        for (int i = 0; i < 3; i++)
                        {
                            levelOpenGL.AddRange(triangle.coordinates[i].X, triangle.coordinates[i].Y, triangle.coordinates[i].Z, triangle.textureCoordinates[i].X, triangle.textureCoordinates[i].Y, triangle.directionIndex);
                        }
                    }
                }
            }

            return [.. levelOpenGL];
        }

        public static void ImportLevelFromFile(string fileLocation, out Level level, out float[] levelGL)
        {

            level = new Level();
            levelGL = [];

            BinaryReader levelFile;

            try
            {
                levelFile = new(File.Open(fileLocation, FileMode.Open));
            }
            catch
            {
                return;
            }
            while (!(levelFile.BaseStream.Position == levelFile.BaseStream.Length))
            {
                Object.ObjectType type = (Object.ObjectType)levelFile.ReadByte();
                switch (type)
                {
                    case Object.ObjectType.None:
                        break;

                    case Object.ObjectType.Triangle:
                        level.levelObjects.Add(new Triangle((levelFile.ReadSingle(), levelFile.ReadSingle(), levelFile.ReadSingle()),
                            (levelFile.ReadSingle(), levelFile.ReadSingle(), levelFile.ReadSingle()),
                            (levelFile.ReadSingle(), levelFile.ReadSingle(), levelFile.ReadSingle()),
                            [(levelFile.ReadSingle(), levelFile.ReadSingle()), (levelFile.ReadSingle(), levelFile.ReadSingle()), (levelFile.ReadSingle(), levelFile.ReadSingle())],
                            levelFile.ReadInt32(), levelFile.ReadSingle()));
                        break;
                    
                    case Object.ObjectType.Plane:
                    
                        break;

                    case Object.ObjectType.Cube:
                        level.levelObjects.Add(new Cube((levelFile.ReadSingle(), levelFile.ReadSingle(), levelFile.ReadSingle()),
                            levelFile.ReadSingle(), levelFile.ReadSingle(), levelFile.ReadSingle(), levelFile.ReadInt32()));
                        break;
                }
            }
            

        }

    }

}